### ISSUE TITLE
Please add a LICENSE file to this repository

### ISSUE THREAD

**Issue by mithro** [cbalint13/nextpnr-anneal#1]
* https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
* https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

**Comment by cbalint13** [comment]
@mithro 

Added BSD (for nextpnr compatibility).

Thanks pointing it out !
